# Generated by Django 3.1.4 on 2020-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviess',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='moviess',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
