# Generated by Django 3.1.4 on 2020-12-05 07:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20201204_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=100)),
                ('expires_in', models.DateField(default=datetime.date(2020, 12, 6))),
                ('expired', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
