# Generated by Django 3.1.4 on 2020-12-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userpasstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPassToken',
        ),
    ]
