# Generated by Django 3.1.4 on 2020-12-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_userpasstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviess',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
