# Generated by Django 3.1.4 on 2020-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_moviess_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviess',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
